
export interface Tool {
  key: string;
  title: string;
  emoji: string;
  description: string;
  flitType: 'image' | 'video' | 'audio' | 'other';
  route?: string;
  prompt?: string;
  isMultiImage?: boolean;
  isSecondaryOptional?: boolean;
  isTwoStep?: boolean;
  stepTwoPrompt?: string;
  primaryUploaderTitle?: string;
  primaryUploaderDescription?: string;
  secondaryUploaderTitle?: string;
  secondaryUploaderDescription?: string;
  isVideo?: boolean;
}

export const TOOLS_DATA: Tool[] = [
  {
    key: 'translation',
    title: 'AI视频换脸',
    emoji: '🧍',
    description: '将您的视频中的人脸替换成图片的人脸',
    flitType: 'video',
    route: '/create?tool=aiFaceSwap',
  },
  {
    key: 'tts',
    title: '文本转语音',
    emoji: '🎤',
    description: '将文本转换为自然流畅的语音，支持多种音色和语言',
    flitType: 'audio',
    route: '/create?tool=tts',
  },
  {
    key: '3dModel',
    title: '3D模型',
    emoji: '🤖',
    description: '将您的照片变成一份3D效果图。',
    flitType: 'image',
    route: '/create?tool=3dModel',
  },
  {
    key: 'customPrompt',
    title: '自定义提示',
    emoji: '✍️',
    description: '描述你能想象到的任何变化。最多可上传两张图片作为参考。',
    flitType: 'image',
    route: '/create?tool=useTool',
    prompt: 'CUSTOM',
    isMultiImage: true,
    isSecondaryOptional: true,
    primaryUploaderTitle: '主图像',
    primaryUploaderDescription: '要编辑的主要图像。',
    secondaryUploaderTitle: '参考图像（可选）',
    secondaryUploaderDescription: '用于风格、内容或上下文的第二张图像。',
  },
  {
    key: 'imageTranslation',
    title: 'AI图片换脸',
    emoji: '🧍',
    description: '将您的主图片人脸替换成参考图片的人脸',
    flitType: 'image',
    route: '/create?tool=aIFacSwapping',
  },
  {
    key: 'aiTemplate',
    title: '创意生图',
    emoji: '🖼️',
    description: '根据选中AI模板生成对应内容',
    flitType: 'image',
    route: '/create?tool=templateUi',
  },
  {
    key: 'figurine',
    title: '3D手办',
    emoji: '🧍',
    description: '将您的照片变成一个可收藏的3D角色手办，并配有包装。',
    flitType: 'image',
    prompt: 'turn this photo into a character figure. Behind it, place a box with the character’s image printed on it, and a computer showing the Blender modeling process on its screen. In front of the box, add a round plastic base with the character figure standing on it. set the scene indoors if possible',
  },
  {
    key: 'funko',
    title: 'Funko Pop公仔',
    emoji: '📦',
    description: '将您的主题重塑为一个可爱的Funko Pop！乙烯基公仔，放在盒子里。',
    flitType: 'image',
    prompt: 'Transform the person into a Funko Pop figure, shown inside and next to its packaging.',
  },
  {
    key: 'lego',
    title: '乐高小人仔',
    emoji: '🧱',
    description: '构建一个乐高小人仔版本的您的主题，准备好玩耍。',
    flitType: 'image',
    prompt: 'Transform the person into a LEGO minifigure, inside its packaging box.',
  },
  {
    key: 'crochet',
    title: '钩针娃娃',
    emoji: '🧶',
    description: '将您的图像变成一个柔软的手工钩针娃娃。',
    flitType: 'image',
    prompt: 'Transform the subject into a handmade crocheted yarn doll with a cute, chibi-style appearance.',
  },
  {
    key: 'cosplay',
    title: '动漫转Cosplay',
    emoji: '🎭',
    description: '将动漫角色变为一张逼真的Cosplay照片。',
    flitType: 'image',
    prompt: 'Generate a highly detailed, realistic photo of a person cosplaying the character in this illustration. Replicate the pose, expression, and framing.',
  },
  {
    key: 'plushie',
    title: '可爱毛绒玩具',
    emoji: '🧸',
    description: '将您的主题转换成一个可爱的、柔软的毛绒玩具。',
    flitType: 'image',
    prompt: 'Turn the person in this photo into a cute, soft plushie doll.',
  },
  {
    key: 'keychain',
    title: '亚克力钥匙扣',
    emoji: '🔑',
    description: '创建一个您的主题的可爱亚克力钥匙扣，非常适合挂在包上。',
    flitType: 'image',
    prompt: 'Turn the subject into a cute acrylic keychain, shown attached to a bag.',
  },
  {
    key: 'hdEnhance',
    title: '高清增强',
    emoji: '🔍',
    description: '放大您的图像，增加清晰度、细节，以获得高分辨率外观。',
    flitType: 'image',
    prompt: 'Enhance this image to high resolution, improving sharpness and clarity.',
  },
  {
    key: 'pose',
    title: '姿势参考',
    emoji: '💃',
    description: '将一张图像中的姿势应用到另一张图像中的角色上。',
    flitType: 'image',
    prompt: 'Apply the pose from the second image to the character in the first image. Render as a professional studio photograph.',
    isMultiImage: true,
    primaryUploaderTitle: '角色',
    primaryUploaderDescription: '主要角色',
    secondaryUploaderTitle: '姿势参考',
    secondaryUploaderDescription: '要应用的姿势',
  },
  {
    key: 'photorealistic',
    title: '转为照片级真实',
    emoji: '🪄',
    description: '将绘画或插图转换为惊人逼真的照片。',
    flitType: 'image',
    prompt: 'Turn this illustration into a photorealistic version.',
  },
  {
    key: 'fashion',
    title: '时尚杂志',
    emoji: '📸',
    description: '为您的照片赋予高级时尚、编辑风格的外观，堪比杂志封面。',
    flitType: 'image',
    prompt: 'Transform the photo into a stylized, ultra-realistic fashion magazine portrait with cinematic lighting.',
  },
  {
    key: 'hyperrealistic',
    title: '超写实',
    emoji: '✨',
    description: '应用一种粗粝、直闪的摄影风格，打造酷炫的超写实氛围。',
    flitType: 'image',
    prompt: 'Generate a hyper-realistic, fashion-style photo with strong, direct flash lighting, grainy texture, and a cool, confident pose.',
  },
  {
    key: 'architecture',
    title: '建筑模型',
    emoji: '🏗️',
    description: '将建筑物转变为精细的微缩建筑模型。',
    flitType: 'image',
    prompt: 'Convert this photo of a building into a miniature architecture model, placed on a cardstock in an indoor setting. Show a computer with modeling software in the background.',
  },
  {
    key: 'productRender',
    title: '产品渲染',
    emoji: '💡',
    description: '将产品草图变成专业的、照片级的3D渲染图。',
    flitType: 'image',
    prompt: 'Turn this product sketch into a photorealistic 3D render with studio lighting.',
  },
  {
    key: 'sodaCan',
    title: '汽水罐设计',
    emoji: '🥤',
    description: '将您的图像包装到汽水罐上，并将其放置在精美的产品照片中。',
    flitType: 'image',
    prompt: 'Design a soda can using this image as the main graphic, and show it in a professional product shot.',
  },
  {
    key: 'industrialDesign',
    title: '工业设计渲染',
    emoji: '🛋️',
    description: '将工业设计草图渲染成在博物馆环境中展示的真实产品。',
    flitType: 'image',
    prompt: 'Turn this industrial design sketch into a realistic product photo, rendered with light brown leather and displayed in a minimalist museum setting.',
  },
  {
    key: 'iphoneWallpaper',
    title: 'iPhone壁纸效果',
    emoji: '📱',
    description: '将您的图片即时转换为时尚的iPhone锁屏界面。',
    flitType: 'image',
    prompt: "Turn the image into an iPhone lock screen wallpaper effect, with the phone's time (01:16), date (Sunday, September 16), and status bar information (battery, signal, etc.), with the flashlight and camera buttons at the bottom, overlaid on the image. The original image should be adapted to a vertical composition that fits a phone screen. The phone is placed on a solid color background of the same color scheme.",
  },
  {
    key: 'colorPalette',
    title: '色板换色',
    emoji: '🎨',
    description: '将图像转换为线稿，然后使用第二张图像作为调色板为其上色。',
    flitType: 'image',
    prompt: 'Turn this image into a clean, hand-drawn line art sketch.',
    isMultiImage: true,
    isTwoStep: true,
    stepTwoPrompt: 'Color the line art using the colors from the second image.',
    primaryUploaderTitle: '原始图像',
    primaryUploaderDescription: '要转换的图像',
    secondaryUploaderTitle: '调色板',
    secondaryUploaderDescription: '颜色参考',
  },
  {
    key: 'videoGeneration',
    title: '视频生成',
    emoji: '🎬',
    description: '通过文本提示和可选图像创建短视频。',
    flitType: 'video',
    prompt: 'CUSTOM',
    isVideo: true,
  },
  {
    key: 'isolate',
    title: '分离并增强',
    emoji: '🎯',
    description: '剪出蒙版中的主体，并创建一个干净、高清的肖像。',
    flitType: 'image',
    prompt: 'Isolate the person in the masked area and generate a high-definition photo of them against a neutral background.',
  },
  {
    key: 'screen3d',
    title: '3D屏幕效果',
    emoji: '📺',
    description: '使您照片中屏幕上的内容呈现出裸眼3D效果。',
    flitType: 'image',
    prompt: 'For an image with a screen, add content that appears to be glasses-free 3D, popping out of the screen.',
  },
  {
    key: 'makeup',
    title: '妆容分析',
    emoji: '💄',
    description: '分析肖像中的妆容，并用红笔标记提出改进建议。',
    flitType: 'image',
    prompt: 'Analyze the makeup in this photo and suggest improvements by drawing with a red pen.',
  },
  {
    key: 'background',
    title: '更换背景',
    emoji: '🪩',
    description: '将现有背景更换为酷炫的复古Y2K美学风格。',
    flitType: 'image',
    prompt: 'Change the background to a Y2K aesthetic style.',
  },
  {
    key: 'addIllustration',
    title: '添加插画',
    emoji: '🧑‍🎨',
    description: '在您的真实世界照片中添加迷人的手绘角色。',
    flitType: 'image',
    prompt: 'Add a cute, cartoon-style illustrated couple into the real-world scene, sitting and talking.',
  },
  {
    key: 'pixelArt',
    title: '像素艺术',
    emoji: '👾',
    description: '将您的图像转换为复古的8位像素艺术。',
    flitType: 'image',
    prompt: 'Redraw the image in the retro 8-bit pixel art style.',
  },
  {
    key: 'watercolor',
    title: '水彩画',
    emoji: '🖌️',
    description: '将您的图像转换为柔和、充满活力的水彩画。',
    flitType: 'image',
    prompt: 'Transform the image into a soft and vibrant watercolor painting.',
  },
  {
    key: 'popArt',
    title: '波普艺术',
    emoji: '🎨',
    description: '以安迪·沃霍尔的大胆风格重新想象您的图像。',
    flitType: 'image',
    prompt: "Reimagine the image in the style of Andy Warhol's pop art, with bold colors and screen-print effects.",
  },
  {
    key: 'comicBook',
    title: '漫画书',
    emoji: '💥',
    description: '将您的照片变成一个经典的漫画书面板。',
    flitType: 'image',
    prompt: 'Convert the image into a classic comic book panel with halftones, bold outlines, and action text.',
  },
  {
    key: 'claymation',
    title: '黏土动画',
    emoji: '🗿',
    description: '将您的图像重现为一个迷人的定格黏土场景。',
    flitType: 'image',
    prompt: 'Recreate the image as a charming stop-motion claymation scene.',
  },
  {
    key: 'ukiyoE',
    title: '浮世绘',
    emoji: '🌊',
    description: '将您的图像重绘为传统的日本木版画。',
    flitType: 'image',
    prompt: 'Redraw the image in the style of a traditional Japanese Ukiyo-e woodblock print.',
  },
  {
    key: 'stainedGlass',
    title: '彩色玻璃',
    emoji: '🪟',
    description: '将您的图像转换为一个充满活力的彩色玻璃窗。',
    flitType: 'image',
    prompt: 'Transform the image into a vibrant stained glass window with dark lead lines.',
  },
  {
    key: 'origami',
    title: '折纸',
    emoji: '🦢',
    description: '用折纸风格重建您的主题。',
    flitType: 'image',
    prompt: 'Reconstruct the subject of the image using folded paper in an origami style.',
  },
  {
    key: 'neonGlow',
    title: '霓虹灯光',
    emoji: '💡',
    description: '用明亮、发光的霓虹灯勾勒您的主题。',
    flitType: 'image',
    prompt: 'Outline the subject in bright, glowing neon lights against a dark background.',
  },
  {
    key: 'doodleArt',
    title: '涂鸦艺术',
    emoji: '✏️',
    description: '在您的图像上覆盖好玩的手绘涂鸦。',
    flitType: 'image',
    prompt: 'Overlay the image with playful, hand-drawn doodle-style illustrations.',
  },
  {
    key: 'vintagePhoto',
    title: '复古照片',
    emoji: '📜',
    description: '为您的图像赋予一种陈旧的、深褐色的复古外观。',
    flitType: 'image',
    prompt: 'Give the image an aged, sepia-toned vintage photograph look from the early 20th century.',
  },
  {
    key: 'blueprintSketch',
    title: '蓝图',
    emoji: '📐',
    description: '将您的图像转换为技术蓝图图纸。',
    flitType: 'image',
    prompt: 'Convert the image into a technical blueprint-style architectural drawing.',
  },
  {
    key: 'glitchArt',
    title: '故障艺术',
    emoji: '📉',
    description: '应用数字故障效果，包括数据融合和像素排序。',
    flitType: 'image',
    prompt: 'Apply a digital glitch effect with datamoshing, pixel sorting, and RGB shifts.',
  },
  {
    key: 'doubleExposure',
    title: '双重曝光',
    emoji: '🏞️',
    description: '在双重曝光中将您的图像与自然场景融合。',
    flitType: 'image',
    prompt: 'Create a double exposure effect, blending the image with a nature scene like a forest or a mountain range.',
  },
  {
    key: 'hologram',
    title: '全息图',
    emoji: '🌐',
    description: '将您的主题投影为一个未来主义的、发光的蓝色全息图。',
    flitType: 'image',
    prompt: 'Project the subject as a futuristic, glowing blue hologram.',
  },
  {
    key: 'lowPoly',
    title: '低多边形',
    emoji: '🔺',
    description: '使用低多边形几何网格重建您的图像。',
    flitType: 'image',
    prompt: 'Reconstruct the image using a low-polygon geometric mesh.',
  },
  {
    key: 'charcoalSketch',
    title: '炭笔素描',
    emoji: '✍🏽',
    description: '将您的图像重绘为一幅戏剧性的、高对比度的炭笔素描。',
    flitType: 'image',
    prompt: 'Redraw the image as a dramatic, high-contrast charcoal sketch on textured paper.',
  },
  {
    key: 'impressionism',
    title: '印象派',
    emoji: '👨‍🎨',
    description: '以印象派杰作的风格重绘您的图像。',
    flitType: 'image',
    prompt: 'Repaint the image in the style of an Impressionist masterpiece, with visible brushstrokes and a focus on light.',
  },
  {
    key: 'cubism',
    title: '立体主义',
    emoji: '🧊',
    description: '以抽象、几何的立体主义风格解构您的主题。',
    flitType: 'image',
    prompt: 'Deconstruct and reassemble the subject in the abstract, geometric style of Cubism.',
  },
  {
    key: 'steampunk',
    title: '蒸汽朋克',
    emoji: '⚙️',
    description: '用齿轮、黄铜和维多利亚时代的技术重新想象您的主题。',
    flitType: 'image',
    prompt: 'Reimagine the subject with steampunk aesthetics, featuring gears, brass, and Victorian-era technology.',
  },
  {
    key: 'fantasyArt',
    title: '奇幻艺术',
    emoji: '🐉',
    description: '将您的图像转变为一幅史诗般的奇幻风格绘画。',
    flitType: 'image',
    prompt: 'Transform the image into an epic fantasy-style painting, with magical elements and dramatic lighting.',
  },
  {
    key: 'graffiti',
    title: '涂鸦',
    emoji: '🎨',
    description: '将您的图像喷绘成砖墙上充满活力的涂鸦。',
    flitType: 'image',
    prompt: 'Spray-paint the image as vibrant graffiti on a brick wall.',
  },
  {
    key: 'minimalistLineArt',
    title: '极简线稿',
    emoji: '〰️',
    description: '将您的图像简化为一条连续的线稿。',
    flitType: 'image',
    prompt: 'Reduce the image to a single, continuous, minimalist line drawing.',
  },
  {
    key: 'storybook',
    title: '故事书',
    emoji: '📖',
    description: '以异想天开的儿童故事书风格重绘您的图像。',
    flitType: 'image',
    prompt: "Redraw the image in the style of a whimsical children's storybook illustration.",
  },
  {
    key: 'thermal',
    title: '热成像',
    emoji: '🌡️',
    description: '应用带有热图调色板的热成像效果。',
    flitType: 'image',
    prompt: 'Apply a thermal imaging effect with a heat map color palette.',
  },
  {
    key: 'risograph',
    title: 'Risograph',
    emoji: '📠',
    description: '模拟粗糙、色彩有限的Risograph印刷效果。',
    flitType: 'image',
    prompt: 'Simulate a risograph print effect with grainy textures and limited, overlapping color layers.',
  },
  {
    key: 'crossStitch',
    title: '十字绣',
    emoji: '🧵',
    description: '将您的图像转换为手工制作的十字绣图案。',
    flitType: 'image',
    prompt: 'Convert the image into a textured, handmade cross-stitch pattern.',
  },
  {
    key: 'tattoo',
    title: '纹身艺术',
    emoji: '🖋️',
    description: '将您的主题重新设计为经典的美式传统纹身。',
    flitType: 'image',
    prompt: 'Redesign the subject as a classic American traditional style tattoo.',
  },
  {
    key: 'psychedelic',
    title: '迷幻风格',
    emoji: '🌀',
    description: '应用20世纪60年代充满活力、旋转的迷幻艺术风格。',
    flitType: 'image',
    prompt: 'Apply a vibrant, swirling, psychedelic art style from the 1960s.',
  },
  {
    key: 'gothic',
    title: '哥特式',
    emoji: '🏰',
    description: '用黑暗的哥特艺术风格重新想象您的场景。',
    flitType: 'image',
    prompt: 'Reimagine the scene with a dark, gothic art style, featuring dramatic shadows and architecture.',
  },
  {
    key: 'tribal',
    title: '部落艺术',
    emoji: '🗿',
    description: '使用传统的部落图案重绘您的主题。',
    flitType: 'image',
    prompt: 'Redraw the subject using patterns and motifs from traditional tribal art.',
  },
  {
    key: 'dotPainting',
    title: '点画',
    emoji: '🎨',
    description: '使用原住民点画技术重新创作您的图像。',
    flitType: 'image',
    prompt: 'Recreate the image using the dot painting technique of Aboriginal art.',
  },
  {
    key: 'chalk',
    title: '粉笔画',
    emoji: '🖍️',
    description: '将您的图像画成人行道上色彩缤纷的粉笔画。',
    flitType: 'image',
    prompt: 'Draw the image as a colorful chalk illustration on a sidewalk.',
  },
  {
    key: 'sandArt',
    title: '沙画',
    emoji: '🏜️',
    description: '重新创作您的图像，仿佛它是由彩色沙子制成的。',
    flitType: 'image',
    prompt: 'Recreate the image as if it were made from colored sand.',
  },
  {
    key: 'mosaic',
    title: '马赛克',
    emoji: '💠',
    description: '将您的图像转换为由小瓷砖制成的马赛克。',
    flitType: 'image',
    prompt: 'Transform the image into a mosaic made of small ceramic tiles.',
  },
  {
    key: 'paperQuilling',
    title: '纸艺',
    emoji: '📜',
    description: '使用卷曲和成形的纸条重建您的主题。',
    flitType: 'image',
    prompt: 'Reconstruct the subject using the art of paper quilling, with rolled and shaped strips of paper.',
  },
  {
    key: 'woodCarving',
    title: '木雕',
    emoji: '🪵',
    description: '将您的主题重塑为精细的木雕。',
    flitType: 'image',
    prompt: 'Recreate the subject as a detailed wood carving.',
  },
  {
    key: 'iceSculpture',
    title: '冰雕',
    emoji: '🧊',
    description: '将您的主题转变为半透明的冰雕。',
    flitType: 'image',
    prompt: 'Transform the subject into a translucent, detailed ice sculpture.',
  },
  {
    key: 'bronzeStatue',
    title: '铜像',
    emoji: '🗿',
    description: '将您的主题变成一尊风化的铜像。',
    flitType: 'image',
    prompt: 'Turn the subject into a weathered bronze statue on a pedestal.',
  },
  {
    key: 'galaxy',
    title: '星系',
    emoji: '🌌',
    description: '将您的图像与充满活力的星云和星空背景融合。',
    flitType: 'image',
    prompt: 'Blend the image with a vibrant nebula and starry galaxy background.',
  },
  {
    key: 'fire',
    title: '火焰',
    emoji: '🔥',
    description: '重新想象您的主题，仿佛它是由熊熊火焰形成的。',
    flitType: 'image',
    prompt: 'Reimagine the subject as if it were formed from roaring flames.',
  },
  {
    key: 'water',
    title: '水',
    emoji: '💧',
    description: '重新想象您的主题，仿佛它是由流动的水形成的。',
    flitType: 'image',
    prompt: 'Reimagine the subject as if it were formed from flowing, liquid water.',
  },
  {
    key: 'smokeArt',
    title: '烟雾艺术',
    emoji: '💨',
    description: '用优雅、旋转的烟雾创造您的主题。',
    flitType: 'image',
    prompt: 'Create the subject from elegant, swirling wisps of smoke.',
  },
  {
    key: 'vectorArt',
    title: '矢量艺术',
    emoji: '🎨',
    description: '将您的照片转换为干净、可缩放的矢量艺术。',
    flitType: 'image',
    prompt: 'Convert the photo into clean, scalable vector art with flat colors and sharp lines.',
  },
  {
    key: 'infrared',
    title: '红外线',
    emoji: '📸',
    description: '模拟具有超现实色彩的红外照片效果。',
    flitType: 'image',
    prompt: 'Simulate an infrared photo effect with surreal colors and glowing foliage.',
  },
  {
    key: 'knitted',
    title: '针织',
    emoji: '🧶',
    description: '将您的图像重塑为一个舒适的针织羊毛图案。',
    flitType: 'image',
    prompt: 'Recreate the image as a cozy, knitted wool pattern.',
  },
  {
    key: 'etching',
    title: '蚀刻',
    emoji: '✒️',
    description: '将您的图像重绘为经典的黑白蚀刻画。',
    flitType: 'image',
    prompt: 'Redraw the image as a classic black and white etching or engraving.',
  },
  {
    key: 'diorama',
    title: '立体模型',
    emoji: '📦',
    description: '将您的场景变成盒子里的微型3D立体模型。',
    flitType: 'image',
    prompt: 'Turn the scene into a miniature 3D diorama inside a box.',
  },
  {
    key: 'paintingProcess',
    title: '绘画过程',
    emoji: '🖼️',
    description: '展示一个4步网格，展示您的图像从草图到最终绘画的创作过程。',
    flitType: 'image',
    prompt: 'Generate a 4-panel grid showing the artistic process of creating this image, from sketch to final render.',
  },
  {
    key: 'markerSketch',
    title: '马克笔素描',
    emoji: '🖊️',
    description: '用Copic马克笔的风格重塑您的照片，创造出充满活力的素描。',
    flitType: 'image',
    prompt: 'Redraw the image in the style of a Copic marker sketch, often used in design.',
  },
  {
    key: 'vanGogh',
    title: '梵高风格',
    emoji: '🌌',
    description: '用梵高《星夜》标志性的、旋转的笔触重绘您的照片。',
    flitType: 'image',
    prompt: "Reimagine the photo in the style of Van Gogh's 'Starry Night'.",
  },
  {
    key: 'cyberpunk',
    title: '赛博朋克',
    emoji: '🤖',
    description: '将您的场景转变为一个充满霓虹灯的未来赛博朋克城市。',
    flitType: 'image',
    prompt: 'Transform the scene into a futuristic cyberpunk city.',
  },
  {
    key: 'lineArt',
    title: '线稿绘画',
    emoji: '✍🏻',
    description: '将您的照片简化为其基本线条，创建一个干净的草图。',
    flitType: 'image',
    prompt: 'Turn the image into a clean, hand-drawn line art sketch.',
  },
];

